baseURL = "https://nicklaw.netlify.com/"
languageCode = "ja"
hasCJKLanguage = true
title = "むだにくろうす"
theme = "beautifulhugo"

metaDataFormat = "toml"
pygmentsUseClasses = true
pygmentsCodeFences = true
defaultContentLanguage = "ja"
paginate = 10
googleAnalytics = "UA-114407960-1"
enableRobotsTXT = true
enableEmoji = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    favicon = ""
    subtitle = "豚リブロース"
    comments = true
    rss = true
    gcse = "003964668609128965357:bcoefz0socq"

[params.staticman]
    api = "https://api.staticman.net/v2/entry/mzsrkeen10/website/master/comments"
    pulls = "https://github.com/mzsrkeen10/website/pulls"

[params.staticman.recaptcha]
    sitekey = "6LfULUcUAAAAANb_rJTMptvFYlEeSyVP3qj2Jqoy"
    secret = "llLQ5De1TWFQPjE2Vd+TctSnWrXuAlGd12jezkVOOg/X+qAFqwUNuuBuVddR2f1uL8+b2KPQRnrUTrBNXLjsXC1r2axszUzhN9xD9/fWlElARV7p9QGXgurstvLfUIMR0JjbMefjOteQrqUqnq+OkD9uvLx39NjMDqpTM2A3oLw="

[author]
    name = "ニクロー"
    twitter = "nicklaw296"
    github = "mzsrkeen10"

[permalinks]
    post = "/post/:year/:month/:day/:slug"

[[menu.main]]
    name = "Post"
    url = "post"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2

[[menu.main]]
    name = "Works"
    url = "page/works/"
    weight = 3
