baseURL = "https://nicklaw.netlify.com/"
languageCode = "ja"
hasCJKLanguage = true
title = "むだにくろうす"
theme = "beautifulhugo"

metaDataFormat = "toml"
pygmentsUseClasses = true
pygmentsCodeFences = true
defaultContentLanguage = "ja"
paginate = 10
googleAnalytics = "UA-114407960-1"
enableRobotsTXT = true
enableEmoji = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    favicon = ""
    subtitle = "豚リブロース"
    rss = true
    gcse = "003964668609128965357:bcoefz0socq"

[params.staticman]
    api = "https://api.staticman.net/v2/entry/mzsrkeen10/website/master/comments"
    pulls = "https://github.com/mzsrkeen10/website/pulls"

[params.staticman.recaptcha]
    sitekey = "6LfULUcUAAAAANb_rJTMptvFYlEeSyVP3qj2Jqoy"
    secret = "qlBYiil8RP0p5lGpKZmU+M5RgQEy9dvDeHlvqMBRsKT5ftBP/N9ufuEn9TqmiPfG/ZWpgl8iYAUmoltxgS/lsIDEA/bpIJ1TNGBXYqdH4uKliIgb6nlsX55Pjrm0P7TEXXx9ClUrJ17YByBT0ILyZEJdLCOC7LPI42s0nJ3aZXA="

[author]
    name = "ニクロー"
    twitter = "nicklaw296"
    github = "mzsrkeen10"

[[menu.main]]
    name = "Post"
    url = "post"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 2
