baseURL = "https://nicklaw296.netlify.com/"
languageCode = "ja"
hasCJKLanguage = true
theme = "ananke"

metaDataFormat = "toml"
defaultContentLanguage = "ja"
sectionPagesMenu = "main"
paginate = 10
googleAnalytics = ""
enableRobotsTXT = true
enableEmoji = true

[sitemap]
    changefreq = "monthly"
    priority = 0.5
    filename = "sitemap.xml"

[params]
    title = "むだにくろうす"
    favicon = ""
    description = ""
    facebook = ""
    twitter = "https://twitter.com/nicklaw296"
    github = "https://github.com/mzsrkeen10"
    instagram = ""
    youtube = ""
    linkedin = ""
    # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
    background_color_class = "bg-black"
    featured_image = "/images/gohugo-default-sample-hero-image.jpg"
    recent_posts_number = 2
